# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Filippo Corti
email: me@filippocorti.net
description: >
  UX/UI designer and web developer.
  Coffee Enthusiast.
  Blogger.
url: https://www.filippocorti.net
twitter_username: philapple
github_username:  philapple

# Build settings
markdown: kramdown
include: [node_modules]
exclude: []

plugins:
  - octopress-autoprefixer
  - jekyll-paginate-v2

# Pagination configuration for notes/blog
pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  sort_field: 'date'
  sort_reverse: true
  permalink: '/page/:num/'
  title: ':title - page :num'

autopages:
  enabled: true
  tags:
    layouts:
      - 'archives.html'
    permalink: 'notes/:tag'
  categories:
    enabled: false
  collections:
    enabled: false


# Header nav
navigation:
- text: Contact me
  url: /hi

# Collections
collections:
  posts:
     permalink: /notes/:year/:month/:title/
  reading:
    defaults:
      path: "reading"
    values:
      layout: reading
  places:
    defaults:
      path: "places"
    values:
      layout: places
