# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Filippo Corti
email: me@filippocorti.net
description: >
  UX designer and web developer.
  Coffee Enthusiast.
  Blogger and .
url: https://www.filippocorti.net
twitter_username: philapple
github_username:  philapple

# Build settings
markdown: kramdown
include: [node_modules]
exclude: []

plugins:
  - octopress-autoprefixer

# Header nav
navigation:
- text: Contact me
  url: /hi

# Collections
collections:
  reading:
    defaults:
      path: "reading"
    values:
      layout: reading
  places:
    defaults:
      path: "places"
    values:
      layout: places
