# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Filippo Corti
email: me@filippocorti.net
description: > # this means to ignore newlines until "baseurl:"
  Blogger, designer and developer from Lecco.
  He drinks a lot of coffee.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://filippocorti.com" # the base hostname & protocol for your site
twitter_username: philapple
github_username:  philapple

# Build settings
markdown: kramdown

# Collections
collections:
  bookshelf:
    defaults:
      path: "library"
    values:
      layout: bookshelf

gems:
  - octopress-autoprefixer
